// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Record message for T1 & T2 columns from database
type Record struct {
	T1_Key               int32                `protobuf:"varint,1,opt,name=T1_Key,json=T1Key,proto3" json:"T1_Key,omitempty"`
	T1_Data              string               `protobuf:"bytes,2,opt,name=T1_Data,json=T1Data,proto3" json:"T1_Data,omitempty"`
	T2_Key               int32                `protobuf:"varint,3,opt,name=T2_Key,json=T2Key,proto3" json:"T2_Key,omitempty"`
	T2_T1Key             int32                `protobuf:"varint,4,opt,name=T2_T1key,json=T2T1key,proto3" json:"T2_T1key,omitempty"`
	T2_Data              string               `protobuf:"bytes,5,opt,name=T2_Data,json=T2Data,proto3" json:"T2_Data,omitempty"`
	T2_CreatedOn         *timestamp.Timestamp `protobuf:"bytes,6,opt,name=T2_CreatedOn,json=T2CreatedOn,proto3" json:"T2_CreatedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetT1_Key() int32 {
	if m != nil {
		return m.T1_Key
	}
	return 0
}

func (m *Record) GetT1_Data() string {
	if m != nil {
		return m.T1_Data
	}
	return ""
}

func (m *Record) GetT2_Key() int32 {
	if m != nil {
		return m.T2_Key
	}
	return 0
}

func (m *Record) GetT2_T1Key() int32 {
	if m != nil {
		return m.T2_T1Key
	}
	return 0
}

func (m *Record) GetT2_Data() string {
	if m != nil {
		return m.T2_Data
	}
	return ""
}

func (m *Record) GetT2_CreatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.T2_CreatedOn
	}
	return nil
}

// Request message for creating a new data entry
type DataRequest struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequest) Reset()         { *m = DataRequest{} }
func (m *DataRequest) String() string { return proto.CompactTextString(m) }
func (*DataRequest) ProtoMessage()    {}
func (*DataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *DataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequest.Unmarshal(m, b)
}
func (m *DataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequest.Marshal(b, m, deterministic)
}
func (m *DataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequest.Merge(m, src)
}
func (m *DataRequest) XXX_Size() int {
	return xxx_messageInfo_DataRequest.Size(m)
}
func (m *DataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequest proto.InternalMessageInfo

func (m *DataRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type DataResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Key                  int32    `protobuf:"varint,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *DataResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DataResponse) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

type DataFilter struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataFilter) Reset()         { *m = DataFilter{} }
func (m *DataFilter) String() string { return proto.CompactTextString(m) }
func (*DataFilter) ProtoMessage()    {}
func (*DataFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}

func (m *DataFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataFilter.Unmarshal(m, b)
}
func (m *DataFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataFilter.Marshal(b, m, deterministic)
}
func (m *DataFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataFilter.Merge(m, src)
}
func (m *DataFilter) XXX_Size() int {
	return xxx_messageInfo_DataFilter.Size(m)
}
func (m *DataFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_DataFilter.DiscardUnknown(m)
}

var xxx_messageInfo_DataFilter proto.InternalMessageInfo

func (m *DataFilter) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type DeleteDataRequest struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDataRequest) Reset()         { *m = DeleteDataRequest{} }
func (m *DeleteDataRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDataRequest) ProtoMessage()    {}
func (*DeleteDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{4}
}

func (m *DeleteDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDataRequest.Unmarshal(m, b)
}
func (m *DeleteDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDataRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDataRequest.Merge(m, src)
}
func (m *DeleteDataRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDataRequest.Size(m)
}
func (m *DeleteDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDataRequest proto.InternalMessageInfo

func (m *DeleteDataRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type DeleteDataResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDataResponse) Reset()         { *m = DeleteDataResponse{} }
func (m *DeleteDataResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDataResponse) ProtoMessage()    {}
func (*DeleteDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{5}
}

func (m *DeleteDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDataResponse.Unmarshal(m, b)
}
func (m *DeleteDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDataResponse.Marshal(b, m, deterministic)
}
func (m *DeleteDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDataResponse.Merge(m, src)
}
func (m *DeleteDataResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDataResponse.Size(m)
}
func (m *DeleteDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDataResponse proto.InternalMessageInfo

func (m *DeleteDataResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *DeleteDataResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Record)(nil), "data.Record")
	proto.RegisterType((*DataRequest)(nil), "data.DataRequest")
	proto.RegisterType((*DataResponse)(nil), "data.DataResponse")
	proto.RegisterType((*DataFilter)(nil), "data.DataFilter")
	proto.RegisterType((*DeleteDataRequest)(nil), "data.DeleteDataRequest")
	proto.RegisterType((*DeleteDataResponse)(nil), "data.DeleteDataResponse")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0xa9, 0x40, 0x0b, 0x03, 0x07, 0xd8, 0xc4, 0x50, 0x7b, 0x11, 0x7b, 0x50, 0x2e, 0x16,
	0xbb, 0xc6, 0xa3, 0x07, 0x95, 0xe8, 0x81, 0x44, 0x93, 0x66, 0xef, 0x4d, 0xa1, 0x23, 0x21, 0xfc,
	0x29, 0xb6, 0x4b, 0x4c, 0x9f, 0xca, 0x77, 0xf0, 0xc9, 0xcc, 0xce, 0xb6, 0x40, 0xd4, 0xc4, 0xc4,
	0xdb, 0xcc, 0xec, 0x6f, 0xbe, 0x7c, 0xdf, 0xee, 0x02, 0xc4, 0x91, 0x8c, 0xbc, 0x4d, 0x9a, 0xc8,
	0x84, 0xd5, 0x54, 0xed, 0x9c, 0xce, 0x92, 0x64, 0xb6, 0xc4, 0x21, 0xcd, 0x26, 0xdb, 0xd7, 0xa1,
	0x9c, 0xaf, 0x30, 0x93, 0xd1, 0x6a, 0xa3, 0x31, 0xf7, 0xd3, 0x00, 0x33, 0xc0, 0x69, 0x92, 0xc6,
	0xec, 0x18, 0x4c, 0xe1, 0x87, 0x63, 0xcc, 0x6d, 0xa3, 0x6f, 0x0c, 0xea, 0x41, 0x5d, 0xf8, 0x63,
	0xcc, 0x59, 0x0f, 0x2c, 0xe1, 0x87, 0xa3, 0x48, 0x46, 0xf6, 0x51, 0xdf, 0x18, 0x34, 0x03, 0x53,
	0xf8, 0xaa, 0x23, 0x9e, 0x13, 0x5f, 0x2d, 0x78, 0xae, 0xf8, 0x13, 0x68, 0x08, 0x1e, 0x0a, 0x7f,
	0x81, 0xb9, 0x5d, 0xa3, 0x03, 0x4b, 0x70, 0x6a, 0x49, 0x8a, 0x6b, 0xa9, 0x7a, 0x21, 0xc5, 0x49,
	0xea, 0x16, 0xda, 0x82, 0x87, 0x0f, 0x29, 0x46, 0x12, 0xe3, 0x97, 0xb5, 0x6d, 0xf6, 0x8d, 0x41,
	0x8b, 0x3b, 0x9e, 0x76, 0xef, 0x95, 0xee, 0x3d, 0x51, 0xba, 0x0f, 0x5a, 0x82, 0xef, 0x70, 0xf7,
	0x0c, 0x5a, 0x4a, 0x26, 0xc0, 0xb7, 0x2d, 0x66, 0x92, 0x31, 0xa0, 0xf0, 0x14, 0xa3, 0x19, 0x50,
	0xed, 0x3e, 0x43, 0x5b, 0x23, 0xd9, 0x26, 0x59, 0x67, 0xf8, 0x1b, 0xc3, 0x6c, 0xb0, 0xb2, 0xed,
	0x74, 0x8a, 0x59, 0x46, 0x49, 0x1b, 0x41, 0xd9, 0xb2, 0x0e, 0x54, 0x17, 0xbb, 0x9c, 0xaa, 0x74,
	0xcf, 0x01, 0x94, 0xde, 0xe3, 0x7c, 0x29, 0x31, 0x55, 0x9b, 0x0b, 0xcc, 0xdf, 0x93, 0x34, 0x2e,
	0x04, 0xcb, 0xd6, 0xbd, 0x80, 0xee, 0x08, 0x97, 0x28, 0xf1, 0x2f, 0x83, 0xf7, 0xc0, 0x0e, 0xc1,
	0xff, 0xd8, 0xe4, 0x1f, 0x06, 0xd4, 0xe8, 0x3e, 0x2f, 0xc1, 0x7a, 0x42, 0x49, 0x65, 0xc7, 0xa3,
	0x4f, 0xb1, 0x37, 0xeb, 0xb4, 0xf5, 0x44, 0xbf, 0xba, 0x5b, 0xb9, 0x32, 0xd8, 0x0d, 0x80, 0xbe,
	0x4c, 0xda, 0xe8, 0xee, 0x37, 0x0a, 0xc3, 0x0e, 0x3b, 0x1c, 0x69, 0x6b, 0x6e, 0x85, 0xdd, 0x01,
	0xec, 0x2d, 0xb3, 0x5e, 0xc1, 0x7c, 0x4f, 0xeb, 0xd8, 0x3f, 0x0f, 0x4a, 0x89, 0x89, 0x49, 0x4f,
	0x7b, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xb1, 0xd1, 0x8b, 0xba, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataClient is the client API for Data service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataClient interface {
	// Get all Data with filter - A server-to-client streaming RPC.
	GetData(ctx context.Context, in *DataFilter, opts ...grpc.CallOption) (Data_GetDataClient, error)
	// Create a new Data - A simple RPC
	CreateData(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error)
	// Delete data - A simple RPC
	DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*DeleteDataResponse, error)
}

type dataClient struct {
	cc *grpc.ClientConn
}

func NewDataClient(cc *grpc.ClientConn) DataClient {
	return &dataClient{cc}
}

func (c *dataClient) GetData(ctx context.Context, in *DataFilter, opts ...grpc.CallOption) (Data_GetDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Data_serviceDesc.Streams[0], "/data.Data/GetData", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataGetDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Data_GetDataClient interface {
	Recv() (*Record, error)
	grpc.ClientStream
}

type dataGetDataClient struct {
	grpc.ClientStream
}

func (x *dataGetDataClient) Recv() (*Record, error) {
	m := new(Record)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataClient) CreateData(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/data.Data/CreateData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*DeleteDataResponse, error) {
	out := new(DeleteDataResponse)
	err := c.cc.Invoke(ctx, "/data.Data/DeleteData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServer is the server API for Data service.
type DataServer interface {
	// Get all Data with filter - A server-to-client streaming RPC.
	GetData(*DataFilter, Data_GetDataServer) error
	// Create a new Data - A simple RPC
	CreateData(context.Context, *DataRequest) (*DataResponse, error)
	// Delete data - A simple RPC
	DeleteData(context.Context, *DeleteDataRequest) (*DeleteDataResponse, error)
}

func RegisterDataServer(s *grpc.Server, srv DataServer) {
	s.RegisterService(&_Data_serviceDesc, srv)
}

func _Data_GetData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DataFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServer).GetData(m, &dataGetDataServer{stream})
}

type Data_GetDataServer interface {
	Send(*Record) error
	grpc.ServerStream
}

type dataGetDataServer struct {
	grpc.ServerStream
}

func (x *dataGetDataServer) Send(m *Record) error {
	return x.ServerStream.SendMsg(m)
}

func _Data_CreateData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).CreateData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Data/CreateData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).CreateData(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_DeleteData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).DeleteData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Data/DeleteData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).DeleteData(ctx, req.(*DeleteDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Data_serviceDesc = grpc.ServiceDesc{
	ServiceName: "data.Data",
	HandlerType: (*DataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateData",
			Handler:    _Data_CreateData_Handler,
		},
		{
			MethodName: "DeleteData",
			Handler:    _Data_DeleteData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetData",
			Handler:       _Data_GetData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "data.proto",
}
